// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"context"
)

type Querier interface {
	CreateSend(ctx context.Context, arg CreateSendParams) (Send, error)
	CreateShorten(ctx context.Context, arg CreateShortenParams) (Shorten, error)
	DeleteSend(ctx context.Context, id int64) error
	DeleteShorten(ctx context.Context, id int64) error
	GetSend(ctx context.Context, id int64) (Send, error)
	GetSendByUrl(ctx context.Context, url string) (Send, error)
	GetShorten(ctx context.Context, id int64) (Shorten, error)
	GetShortenByUrl(ctx context.Context, url string) (Shorten, error)
	ListSend(ctx context.Context) ([]Send, error)
	UpdateSend(ctx context.Context, arg UpdateSendParams) (Send, error)
}

var _ Querier = (*Queries)(nil)
