// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: send.sql

package database

import (
	"context"
	"database/sql"
)

const createSend = `-- name: CreateSend :one
INSERT INTO send (
  url, file, size, permanent
) VALUES (
  $1, $2, $3, $4
) RETURNING id, url, file, size, permanent, created_at, updated_at
`

type CreateSendParams struct {
	Url       string `json:"url"`
	File      string `json:"file"`
	Size      string `json:"size"`
	Permanent bool   `json:"permanent"`
}

func (q *Queries) CreateSend(ctx context.Context, arg CreateSendParams) (Send, error) {
	row := q.db.QueryRowContext(ctx, createSend,
		arg.Url,
		arg.File,
		arg.Size,
		arg.Permanent,
	)
	var i Send
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.File,
		&i.Size,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSend = `-- name: DeleteSend :exec
DELETE FROM send
WHERE id = $1
`

func (q *Queries) DeleteSend(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSend, id)
	return err
}

const getSend = `-- name: GetSend :one
SELECT id, url, file, size, permanent, created_at, updated_at FROM send
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSend(ctx context.Context, id int64) (Send, error) {
	row := q.db.QueryRowContext(ctx, getSend, id)
	var i Send
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.File,
		&i.Size,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSendByUrl = `-- name: GetSendByUrl :one
SELECT id, url, file, size, permanent, created_at, updated_at FROM send
WHERE url = $1 LIMIT 1
`

func (q *Queries) GetSendByUrl(ctx context.Context, url string) (Send, error) {
	row := q.db.QueryRowContext(ctx, getSendByUrl, url)
	var i Send
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.File,
		&i.Size,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSend = `-- name: ListSend :many
SELECT id, url, file, size, permanent, created_at, updated_at FROM send
ORDER BY updated_at
`

func (q *Queries) ListSend(ctx context.Context) ([]Send, error) {
	rows, err := q.db.QueryContext(ctx, listSend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Send
	for rows.Next() {
		var i Send
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.File,
			&i.Size,
			&i.Permanent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSend = `-- name: UpdateSend :one
UPDATE send
set url = $2,
    file = $3,
    size = $4,
    permanent = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, url, file, size, permanent, created_at, updated_at
`

type UpdateSendParams struct {
	ID        int64        `json:"id"`
	Url       string       `json:"url"`
	File      string       `json:"file"`
	Size      string       `json:"size"`
	Permanent bool         `json:"permanent"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpdateSend(ctx context.Context, arg UpdateSendParams) (Send, error) {
	row := q.db.QueryRowContext(ctx, updateSend,
		arg.ID,
		arg.Url,
		arg.File,
		arg.Size,
		arg.Permanent,
		arg.UpdatedAt,
	)
	var i Send
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.File,
		&i.Size,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
