// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: shorten.sql

package database

import (
	"context"
	"database/sql"
)

const createShorten = `-- name: CreateShorten :one
INSERT INTO shorten (
  url, target, permanent
) VALUES (
  $1, $2, $3
) RETURNING id, url, target, permanent, created_at, updated_at
`

type CreateShortenParams struct {
	Url       string `json:"url"`
	Target    string `json:"target"`
	Permanent bool   `json:"permanent"`
}

func (q *Queries) CreateShorten(ctx context.Context, arg CreateShortenParams) (Shorten, error) {
	row := q.db.QueryRowContext(ctx, createShorten, arg.Url, arg.Target, arg.Permanent)
	var i Shorten
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Target,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShorten = `-- name: DeleteShorten :exec
DELETE FROM shorten
WHERE id = $1
`

func (q *Queries) DeleteShorten(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteShorten, id)
	return err
}

const getShorten = `-- name: GetShorten :one
SELECT id, url, target, permanent, created_at, updated_at FROM shorten
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetShorten(ctx context.Context, id int64) (Shorten, error) {
	row := q.db.QueryRowContext(ctx, getShorten, id)
	var i Shorten
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Target,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortenByUrl = `-- name: GetShortenByUrl :one
SELECT id, url, target, permanent, created_at, updated_at FROM shorten
WHERE url = $1 LIMIT 1
`

func (q *Queries) GetShortenByUrl(ctx context.Context, url string) (Shorten, error) {
	row := q.db.QueryRowContext(ctx, getShortenByUrl, url)
	var i Shorten
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Target,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShorten = `-- name: UpdateShorten :one
UPDATE shorten
set url = $2,
    target = $3,
    permanent = $4,
    updated_at = $5
WHERE id = $1
RETURNING id, url, target, permanent, created_at, updated_at
`

type UpdateShortenParams struct {
	ID        int64        `json:"id"`
	Url       string       `json:"url"`
	Target    string       `json:"target"`
	Permanent bool         `json:"permanent"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpdateShorten(ctx context.Context, arg UpdateShortenParams) (Shorten, error) {
	row := q.db.QueryRowContext(ctx, updateShorten,
		arg.ID,
		arg.Url,
		arg.Target,
		arg.Permanent,
		arg.UpdatedAt,
	)
	var i Shorten
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Target,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
