on: workflow_call

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgre14-for-testing

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Setup Database
        run: |
          docker exec -i postgre14-for-testing createdb --username=postgres sns
          make migrate

      - name: Test
        run: |
          export DB_NAME=sns
          export DB_HOST=127.0.0.1
          export DB_PORT=5432
          export DB_USER=postgres
          export DB_PASS=postgres
          go test -v ./...
