on: workflow_call

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Build
        run: go build -v ./...

      - name: Set up Mockery
        run: |
          go install github.com/vektra/mockery/v2@v2.24.0
          mockery

      - name: Test
        run: go test -v ./...
