on: workflow_call

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Setup Docker
        run: DBPORT=5450 make setup-docker

      - name: Setup Database
        run: |
          docker exec -i postgre14-for-testing createdb --username=postgres sns
          DBPORT=5450 make migrate

      - name: Test
        run: go test -v ./...
